package modelo.entidad;
// Generated 20-nov-2017 17:28:13 by Hibernate Tools 4.3.1



/**
 * Bodegasclientes generated by hbm2java
 */
public class Bodegasclientes  implements java.io.Serializable {


     private Integer idRegistro;
     private Bodegas bodegas;
     private Cliente cliente;

    public Bodegasclientes() {
    }

    public Bodegasclientes(Bodegas bodegas, Cliente cliente) {
       this.bodegas = bodegas;
       this.cliente = cliente;
    }
   
    public Integer getIdRegistro() {
        return this.idRegistro;
    }
    
    public void setIdRegistro(Integer idRegistro) {
        this.idRegistro = idRegistro;
    }
    public Bodegas getBodegas() {
        return this.bodegas;
    }
    
    public void setBodegas(Bodegas bodegas) {
        this.bodegas = bodegas;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }




}


