package modelo.entidad;
// Generated 20-nov-2017 17:28:13 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer idCliente;
     private String nombre;
     private String representante;
     private String telefono;
     private String correo;
     private Date fechaUnion;
     private Set<Producto> productos = new HashSet<Producto>(0);
     private Set<Bodegasclientes> bodegasclienteses = new HashSet<Bodegasclientes>(0);
     private Set<Factura> facturas = new HashSet<Factura>(0);

    public Cliente() {
    }

	
    public Cliente(String nombre, String representante) {
        this.nombre = nombre;
        this.representante = representante;
    }
    public Cliente(String nombre, String representante, String telefono, String correo, Date fechaUnion, Set<Producto> productos, Set<Bodegasclientes> bodegasclienteses, Set<Factura> facturas) {
       this.nombre = nombre;
       this.representante = representante;
       this.telefono = telefono;
       this.correo = correo;
       this.fechaUnion = fechaUnion;
       this.productos = productos;
       this.bodegasclienteses = bodegasclienteses;
       this.facturas = facturas;
    }
   
    public Integer getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getRepresentante() {
        return this.representante;
    }
    
    public void setRepresentante(String representante) {
        this.representante = representante;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public Date getFechaUnion() {
        return this.fechaUnion;
    }
    
    public void setFechaUnion(Date fechaUnion) {
        this.fechaUnion = fechaUnion;
    }
    public Set<Producto> getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set<Producto> productos) {
        this.productos = productos;
    }
    public Set<Bodegasclientes> getBodegasclienteses() {
        return this.bodegasclienteses;
    }
    
    public void setBodegasclienteses(Set<Bodegasclientes> bodegasclienteses) {
        this.bodegasclienteses = bodegasclienteses;
    }
    public Set<Factura> getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set<Factura> facturas) {
        this.facturas = facturas;
    }




}


