package modelo.entidad;
// Generated 20-nov-2017 17:28:13 by Hibernate Tools 4.3.1



/**
 * Factura generated by hbm2java
 */
public class Factura  implements java.io.Serializable {


     private Integer idFactura;
     private Bodegas bodegas;
     private Cliente cliente;
     private Tipopago tipopago;
     private String estado;

    public Factura() {
    }

    public Factura(Bodegas bodegas, Cliente cliente, Tipopago tipopago, String estado) {
       this.bodegas = bodegas;
       this.cliente = cliente;
       this.tipopago = tipopago;
       this.estado = estado;
    }
   
    public Integer getIdFactura() {
        return this.idFactura;
    }
    
    public void setIdFactura(Integer idFactura) {
        this.idFactura = idFactura;
    }
    public Bodegas getBodegas() {
        return this.bodegas;
    }
    
    public void setBodegas(Bodegas bodegas) {
        this.bodegas = bodegas;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Tipopago getTipopago() {
        return this.tipopago;
    }
    
    public void setTipopago(Tipopago tipopago) {
        this.tipopago = tipopago;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


