package modelo.entidad;
// Generated 20-nov-2017 17:28:13 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Privilegios generated by hbm2java
 */
public class Privilegios  implements java.io.Serializable {


     private Integer idPrivilegio;
     private String privilegio;
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);

    public Privilegios() {
    }

	
    public Privilegios(String privilegio) {
        this.privilegio = privilegio;
    }
    public Privilegios(String privilegio, Set<Usuario> usuarios) {
       this.privilegio = privilegio;
       this.usuarios = usuarios;
    }
   
    public Integer getIdPrivilegio() {
        return this.idPrivilegio;
    }
    
    public void setIdPrivilegio(Integer idPrivilegio) {
        this.idPrivilegio = idPrivilegio;
    }
    public String getPrivilegio() {
        return this.privilegio;
    }
    
    public void setPrivilegio(String privilegio) {
        this.privilegio = privilegio;
    }
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }




}


