package modelo.entidad;
// Generated 20-nov-2017 17:28:13 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Registrosalida generated by hbm2java
 */
public class Registrosalida  implements java.io.Serializable {


     private Integer idRegistroSalida;
     private Producto producto;
     private Usuario usuario;
     private int cantidad;
     private Date fechaSalida;

    public Registrosalida() {
    }

	
    public Registrosalida(Producto producto, Usuario usuario, int cantidad) {
        this.producto = producto;
        this.usuario = usuario;
        this.cantidad = cantidad;
    }
    public Registrosalida(Producto producto, Usuario usuario, int cantidad, Date fechaSalida) {
       this.producto = producto;
       this.usuario = usuario;
       this.cantidad = cantidad;
       this.fechaSalida = fechaSalida;
    }
   
    public Integer getIdRegistroSalida() {
        return this.idRegistroSalida;
    }
    
    public void setIdRegistroSalida(Integer idRegistroSalida) {
        this.idRegistroSalida = idRegistroSalida;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public Date getFechaSalida() {
        return this.fechaSalida;
    }
    
    public void setFechaSalida(Date fechaSalida) {
        this.fechaSalida = fechaSalida;
    }




}


