package modelo.entidad;
// Generated 20-nov-2017 17:28:13 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Registroentradas generated by hbm2java
 */
public class Registroentradas  implements java.io.Serializable {


     private Integer idRegistroEntrada;
     private Producto producto;
     private Usuario usuario;
     private int cantidad;
     private Date fechaRecibida;

    public Registroentradas() {
    }

	
    public Registroentradas(Producto producto, Usuario usuario, int cantidad) {
        this.producto = producto;
        this.usuario = usuario;
        this.cantidad = cantidad;
    }
    public Registroentradas(Producto producto, Usuario usuario, int cantidad, Date fechaRecibida) {
       this.producto = producto;
       this.usuario = usuario;
       this.cantidad = cantidad;
       this.fechaRecibida = fechaRecibida;
    }
   
    public Integer getIdRegistroEntrada() {
        return this.idRegistroEntrada;
    }
    
    public void setIdRegistroEntrada(Integer idRegistroEntrada) {
        this.idRegistroEntrada = idRegistroEntrada;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public Date getFechaRecibida() {
        return this.fechaRecibida;
    }
    
    public void setFechaRecibida(Date fechaRecibida) {
        this.fechaRecibida = fechaRecibida;
    }




}


