package modelo.entidad;
// Generated 20-nov-2017 17:28:13 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tipoproducto generated by hbm2java
 */
public class Tipoproducto  implements java.io.Serializable {


     private Integer idTipo;
     private String tipo;
     private String descripcion;
     private String temperaturaAmbiente;
     private Set<Producto> productos = new HashSet<Producto>(0);

    public Tipoproducto() {
    }

	
    public Tipoproducto(String tipo, String descripcion, String temperaturaAmbiente) {
        this.tipo = tipo;
        this.descripcion = descripcion;
        this.temperaturaAmbiente = temperaturaAmbiente;
    }
    public Tipoproducto(String tipo, String descripcion, String temperaturaAmbiente, Set<Producto> productos) {
       this.tipo = tipo;
       this.descripcion = descripcion;
       this.temperaturaAmbiente = temperaturaAmbiente;
       this.productos = productos;
    }
   
    public Integer getIdTipo() {
        return this.idTipo;
    }
    
    public void setIdTipo(Integer idTipo) {
        this.idTipo = idTipo;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getTemperaturaAmbiente() {
        return this.temperaturaAmbiente;
    }
    
    public void setTemperaturaAmbiente(String temperaturaAmbiente) {
        this.temperaturaAmbiente = temperaturaAmbiente;
    }
    public Set<Producto> getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set<Producto> productos) {
        this.productos = productos;
    }




}


