package modelo.entidad;
// Generated 20-nov-2017 17:28:13 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tipopago generated by hbm2java
 */
public class Tipopago  implements java.io.Serializable {


     private Integer idTipoPago;
     private String tipoPago;
     private Set<Factura> facturas = new HashSet<Factura>(0);

    public Tipopago() {
    }

	
    public Tipopago(String tipoPago) {
        this.tipoPago = tipoPago;
    }
    public Tipopago(String tipoPago, Set<Factura> facturas) {
       this.tipoPago = tipoPago;
       this.facturas = facturas;
    }
   
    public Integer getIdTipoPago() {
        return this.idTipoPago;
    }
    
    public void setIdTipoPago(Integer idTipoPago) {
        this.idTipoPago = idTipoPago;
    }
    public String getTipoPago() {
        return this.tipoPago;
    }
    
    public void setTipoPago(String tipoPago) {
        this.tipoPago = tipoPago;
    }
    public Set<Factura> getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set<Factura> facturas) {
        this.facturas = facturas;
    }




}


