package modelo.entidad;
// Generated 20-nov-2017 17:28:13 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private Privilegios privilegios;
     private String usuario;
     private String passwords;
     private String nombreUsuario;
     private char estado;
     private Set<Registroentradas> registroentradases = new HashSet<Registroentradas>(0);
     private Set<Registrosalida> registrosalidas = new HashSet<Registrosalida>(0);

    public Usuario() {
    }

	
    public Usuario(Privilegios privilegios, String usuario, String passwords, String nombreUsuario, char estado) {
        this.privilegios = privilegios;
        this.usuario = usuario;
        this.passwords = passwords;
        this.nombreUsuario = nombreUsuario;
        this.estado = estado;
    }
    public Usuario(Privilegios privilegios, String usuario, String passwords, String nombreUsuario, char estado, Set<Registroentradas> registroentradases, Set<Registrosalida> registrosalidas) {
       this.privilegios = privilegios;
       this.usuario = usuario;
       this.passwords = passwords;
       this.nombreUsuario = nombreUsuario;
       this.estado = estado;
       this.registroentradases = registroentradases;
       this.registrosalidas = registrosalidas;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Privilegios getPrivilegios() {
        return this.privilegios;
    }
    
    public void setPrivilegios(Privilegios privilegios) {
        this.privilegios = privilegios;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getPasswords() {
        return this.passwords;
    }
    
    public void setPasswords(String passwords) {
        this.passwords = passwords;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }
    public Set<Registroentradas> getRegistroentradases() {
        return this.registroentradases;
    }
    
    public void setRegistroentradases(Set<Registroentradas> registroentradases) {
        this.registroentradases = registroentradases;
    }
    public Set<Registrosalida> getRegistrosalidas() {
        return this.registrosalidas;
    }
    
    public void setRegistrosalidas(Set<Registrosalida> registrosalidas) {
        this.registrosalidas = registrosalidas;
    }




}


